

[workspace]
resolver = "2"
members = ["wgpu", "jni"]

[patch.crates-io]
android-activity = { git = 'https://github.com/markkimsal/android-activity.git', branch = 'features/0.6.0-expose-main-looper' }
